name: CICD
on: 
  push: 
    branches:
      - qa
jobs:
  build:
    name: build-deploy-to-sandbox
    environment: qa
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Dependency
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - name:  Build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build # will run `yarn build` command
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_HOST }}
      - name: Adding known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts          
      - name: Copy Package
        run: |
          rm -rf prod-build
          mkdir prod-build
          mkdir prod-build/modules
          cp -r  packages/core/build prod-build/modules/core
          cp -r  packages/classes/build prod-build/modules/classes
          cp -r  packages/attendance/build prod-build/modules/attendance
          cp -r  packages/timetable/build prod-build/modules/timetable
          cp -r  packages/worksheet/build prod-build/modules/worksheet
          cp -r  packages/student/build prod-build/modules/student
          cp -r  packages/teacher-app/build/* prod-build/
          find  prod-build -name  'modules.json' | xargs sed -i 's|http://localhost:[0-9]*||g'
          cd prod-build && tar -cf ../shiksha-ui.tar . && cd ../
          rsync shiksha-ui.tar ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/sandbox.shikshaplatform.io/shiksha-ui.tar
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/sandbox.shikshaplatform.io/public
            rm -rf *
            cp ../shiksha-ui.tar ./
            tar -xvf shiksha-ui.tar .